name: Twitch Stream Checker
on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

jobs:
  check-stream:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download previous status
        uses: actions/download-artifact@v4
        with:
          name: stream-status
          path: .
        continue-on-error: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run stream checker
        env:
          TWITCH_CLIENT_ID: ${{ secrets.TWITCH_CLIENT_ID }}
          TWITCH_CLIENT_SECRET: ${{ secrets.TWITCH_CLIENT_SECRET }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHANNEL: ${{ secrets.TELEGRAM_CHANNEL }}
        run: python bot.py

      - name: Upload current status
        uses: actions/upload-artifact@v4
        with:
          name: stream-status
          path: last_status.json
          retention-days: 1