name: Twitch Stream Monitor
on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run stream monitor
        env:
          TWITCH_CLIENT_ID: ${{ secrets.TWITCH_CLIENT_ID }}
          TWITCH_CLIENT_SECRET: ${{ secrets.TWITCH_CLIENT_SECRET }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHANNEL: ${{ secrets.TELEGRAM_CHANNEL }}
        run: |
          echo "=== STARTING MONITOR ==="
          PYTHON=${{ github.workspace }} python bot.py
          echo "=== MONITOR FINISHED ==="

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: bot-logs
          path: |
            bot.log
            status.json